<a href="https://colab.research.google.com/github/surajkumar071/Anything/blob/main/DataScience.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# `Lab-01 Date - 19/08/2025`

In [1]:
import numpy as np

In [2]:
np.zeros(10) # It prints 10 zeroes

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros(6) # It prints 6 zeroes

array([0., 0., 0., 0., 0., 0.])

In [4]:
np.ones(5) # It prints 5 ones

array([1., 1., 1., 1., 1.])

In [5]:
np.twos(10) # It throws an error

AttributeError: module 'numpy' has no attribute 'twos'

# `Lab-02 Date - 02/09/2025`

In [6]:
np.arange(5,20) # It gives the number b/w 5 to 20 here 5 is included and 20 is excluded

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
np.arange(1,26) # It gives the number b/w 1 to 26 here 1 is included and 26 is excluded

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [8]:
np.arange(1,26,3) # It gives the number b/w 1 to 26 here 1 is included and 26 is excluded and the number is printed by the gap of 3

array([ 1,  4,  7, 10, 13, 16, 19, 22, 25])

In [9]:
np.arange(1,26).reshape(5,5) # arange function gives the number b/w 1 to 26 and reshape function converts into matrix of 5X5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [10]:
np.arange(1,26).reshape(5,4)

ValueError: cannot reshape array of size 25 into shape (5,4)

In [11]:
np.arange(1,31).reshape(6,5) # arange function gives the number b/w 1 to 31 and reshape function converts into matrix of 6X5

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [12]:
np.random.random() # It prints the random number

0.43068322140330817

In [13]:
np.random.randint(5,10) # It prints the random number b/w 5 to 10

9

In [14]:
np.random.randint(5,10,2) # It prints the 2 random number b/w 5 to 10

array([9, 7])

In [15]:
np.random.randint(5,100,20) # It prints the 20 random number b/w 5 to 100

array([39, 22, 39, 57, 51, 32, 98,  7, 43, 84, 94, 72, 17, 87, 79, 94, 52,
       52, 22, 98])

In [16]:
np.arange(1,101,1).reshape(10,10) #It gives a matrix of 10X10

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [17]:
arr = np.random.randint(0,50,10)#It stores the random value into the array
arr #It prints the stored random value without using print function

array([ 4, 32, 16,  2, 31, 11, 49, 10,  0,  3])

In [18]:
arr.min()#It shows minimum value

np.int64(0)

In [19]:
arr.argmin() #index of minimum element

np.int64(8)

In [20]:
arr.max() #It shows maximum value

np.int64(49)

In [21]:
arr.argmax() #index of max. element

np.int64(6)

In [22]:
arr = np.random.randint(0,50,(3,5)) # It converts the random value into a matrix
arr

array([[ 3,  8, 33, 44, 21],
       [ 8, 49, 27, 25, 11],
       [ 6, 49, 23, 21, 43]])

In [23]:
print(arr.max())
print(arr.argmax())

49
6


In [24]:
np.linspace(0,1,5) #linspace means Linear Space // It gives 5 random numbers b/w 0 to 1

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [25]:
np.linspace(0,10,50) #It gives 50 random numbers b/w 0 to 10

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

# `Lab-03 Date - 09/09/2025`

### `Program 01`

In [26]:
from sklearn.preprocessing import LabelEncoder
cat = ['red','green','blue','green','red']
le = LabelEncoder()
lc = le.fit_transform(cat)
print(cat)
print(lc)

['red', 'green', 'blue', 'green', 'red']
[2 1 0 1 2]


In [27]:
from sklearn.preprocessing import LabelEncoder
name = ['Suraj','Sandip','Rahul','Priya','Ashu','Priya','Suraj','Sandip','Rahul','Priya','Ashu','Priya']
le = LabelEncoder()
lc = le.fit_transform(name)
print(name)
print(lc)

['Suraj', 'Sandip', 'Rahul', 'Priya', 'Ashu', 'Priya', 'Suraj', 'Sandip', 'Rahul', 'Priya', 'Ashu', 'Priya']
[4 3 2 1 0 1 4 3 2 1 0 1]


### `Program 02`

In [28]:
from sklearn.preprocessing import LabelEncoder
import pandas as pd
data = pd.DataFrame({'fruit':['apple','banana','orange','apple','orange'],
                    'price':[1.5,2.0,1,0.7,0.5]})
le = LabelEncoder()
data['Enc'] = le.fit_transform(data['fruit'])
print(data)
print("Cat_map",le.classes_)

    fruit  price  Enc
0   apple    1.5    0
1  banana    2.0    1
2  orange    1.0    2
3   apple    0.7    0
4  orange    0.5    2
Cat_map ['apple' 'banana' 'orange']
